name: Auto Hotfix If Needed

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto Hotfix If Needed
        uses: Kibibit/gitflow-hotfix@v1.0.0
        with:
          token: ${{ secrets.BOT_TOKEN }}
          hotfixAgainstBranch: main
          openPrAgainstBranch: beta
